# Generated by Django 4.1 on 2025-04-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="user",
        ),
        migrations.RemoveField(
            model_name="leaderboard",
            name="user",
        ),
        migrations.RemoveField(
            model_name="team",
            name="members",
        ),
        migrations.DeleteModel(
            name="Workout",
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
        migrations.DeleteModel(
            name="Leaderboard",
        ),
        migrations.DeleteModel(
            name="Team",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
